apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: yellowbooks

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - postgres/statefulset.yaml
  - postgres/service.yaml
  - redis/deployment.yaml
  - redis/service.yaml
  - api/deployment.yaml
  - api/service.yaml
  - api/hpa.yaml
  - frontend/deployment.yaml
  - frontend/service.yaml
  - frontend/hpa.yaml
  - ingress/alb-ingress.yaml

commonLabels:
  app.kubernetes.io/name: yelbook
  app.kubernetes.io/managed-by: kustomize
